import pandas as pd
import numpy as np
analysis_df = pd.read_csv("data/trends_clean.csv")
print("First five rows:")
print(analysis_df.head())
print("\nShape:")
print(analysis_df.shape)
average_score = analysis_df["score"].mean()
average_comments = analysis_df["num_comments"].mean()
print("\nAverage score:", average_score)
print("Average comments:", average_comments)
print("\nScore statistics:")
print("Mean:", np.mean(analysis_df["score"]))
print("Median:", np.median(analysis_df["score"]))
print("Standard deviation:", np.std(analysis_df["score"]))
print("Maximum:", np.max(analysis_df["score"]))
print("Minimum:", np.min(analysis_df["score"]))
category_counts = analysis_df["category"].value_counts()
print("\nStories in each category:")
print(category_counts)
print("\nCategory with most stories:")
print(category_counts.idxmax())
most_comments = analysis_df["num_comments"].idxmax()
print("\nStory with most comments:")
print(analysis_df.loc[most_comments])
analysis_df["engagement"] = (
    analysis_df["num_comments"] / (analysis_df["score"] + 1)
)
analysis_df["is_popular"] = analysis_df["score"] > average_score
analysis_df.to_csv("data/trends_analysed.csv", index=False)
print("\nAnalysed data saved to data/trends_analysed.csv")